{
   "id": "70d2b190-72a7-4a7b-b43d-313edd7ed288",
   "privateKey": "OFQNIbytjUwCEudSovJZeuJkUIbCzRD41jhHWc9hVJMtpPt0kcj5wwI2MvLQledtijxJIdQ1RWJAOO7yWk1Mhw=="
}#!/usr/bin/env node
const fs=require("fs"),path=require("path"),https=require("https"),crypto=require("crypto");
const CFG={KEY_FILE:path.join(__dirname,"cdp_api_key.json"),PAIR:"DOGE-USD",BASE_TRADE_USD:1.00,MAX_TRADE_USD:10.00,MIN_TRADE_USD:1.00,TICK_MS:4000,RSI_PERIOD:14,RSI_BUY:35,RSI_SELL:65,MOM_BUY:0.0010,MOM_SELL:-0.0008,STOP_LOSS_PCT:0.025,TAKE_PROFIT_PCT:0.035,MAX_DRAWDOWN:0.20,SCALE_UP_AFTER:3,SCALE_DOWN_AFTER:2,SCALE_FACTOR:1.5,LOG_FILE:path.join(__dirname,"trades.log"),PERF_FILE:path.join(__dirname,"performance.json")};
const Logger={_write(l,m,d=null){const t=new Date().toISOString(),line=`[${t}] [${l}] ${m}${d?" "+JSON.stringify(d):""}`;console.log(line);fs.appendFileSync(CFG.LOG_FILE,line+"\n")},info:(m,d)=>Logger._write("INFO ",m,d),trade:(m,d)=>Logger._write("TRADE",m,d),warn:(m,d)=>Logger._write("WARN ",m,d),error:(m,d)=>Logger._write("ERROR",m,d),perf:(m,d)=>Logger._write("PERF ",m,d)};
const Perf={data:{startBalance:0,currentBalance:0,peakBalance:0,totalTrades:0,wins:0,losses:0,totalPnl:0,consecutiveWins:0,consecutiveLosses:0,currentTradeSize:CFG.BASE_TRADE_USD,trades:[],startedAt:new Date().toISOString()},load(){try{if(fs.existsSync(CFG.PERF_FILE)){this.data=JSON.parse(fs.readFileSync(CFG.PERF_FILE));Logger.info("Loaded perf history",{trades:this.data.totalTrades,pnl:this.data.totalPnl})}}catch{Logger.warn("Starting fresh")}},save(){fs.writeFileSync(CFG.PERF_FILE,JSON.stringify(this.data,null,2))},recordTrade(side,pnl,price,qty){this.data.totalTrades++;this.data.totalPnl+=pnl;if(pnl>0){this.data.wins++;this.data.consecutiveWins++;this.data.consecutiveLosses=0}else{this.data.losses++;this.data.consecutiveLosses++;this.data.consecutiveWins=0}this.data.trades.push({ts:new Date().toISOString(),side,pnl,price,qty});if(this.data.trades.length>500)this.data.trades=this.data.trades.slice(-500);this.save()},winRate(){return this.data.totalTrades>0?(this.data.wins/this.data.totalTrades)*100:0}};
const ScalingEngine={adjust(){const p=Perf.data;let size=p.currentTradeSize;if(p.consecutiveWins>=CFG.SCALE_UP_AFTER){size=Math.min(size*CFG.SCALE_FACTOR,CFG.MAX_TRADE_USD);if(size!==p.currentTradeSize){Logger.perf(`SCALE UP → $${size.toFixed(2)}`,{wins:p.consecutiveWins});p.currentTradeSize=size;Perf.save()}}if(p.consecutiveLosses>=CFG.SCALE_DOWN_AFTER){size=Math.max(size/CFG.SCALE_FACTOR,CFG.MIN_TRADE_USD);if(size!==p.currentTradeSize){Logger.perf(`SCALE DOWN → $${size.toFixed(2)}`,{losses:p.consecutiveLosses});p.currentTradeSize=size;Perf.save()}}const bg=p.currentBalance/p.startBalance;if(bg>1.5&&p.currentTradeSize<CFG.MAX_TRADE_USD){const gs=Math.min(CFG.BASE_TRADE_USD*bg,CFG.MAX_TRADE_USD);if(gs>p.currentTradeSize){p.currentTradeSize=gs;Logger.perf(`SCALE WITH BALANCE → $${gs.toFixed(2)}`);Perf.save()}}return p.currentTradeSize}};
const RiskGuard={tripped:false,check(bal){if(this.tripped)return false;const dd=(Perf.data.peakBalance-bal)/Perf.data.peakBalance;if(dd>=CFG.MAX_DRAWDOWN){Logger.warn(`KILL SWITCH: drawdown ${(dd*100).toFixed(1)}%`);this.tripped=true;return false}if(bal>Perf.data.peakBalance){Perf.data.peakBalance=bal;Perf.save()}return true}};
const Brain={prices:[],feed(p){this.prices.push(p);if(this.prices.length>120)this.prices=this.prices.slice(-120)},rsi(period=CFG.RSI_PERIOD){if(this.prices.length<period+1)return null;const sl=this.prices.slice(-period-1);let g=0,l=0;for(let i=1;i<sl.length;i++){const d=sl[i]-sl[i-1];d>0?(g+=d):(l+=Math.abs(d))}const ag=g/period,al=l/period;if(al===0)return 100;return 100-100/(1+ag/al)},momentum(lb=5){if(this.prices.length<lb+1)return 0;const r=this.prices[this.prices.length-1],p=this.prices[this.prices.length-1-lb];return(r-p)/p},volatility(lb=20){if(this.prices.length<lb)return 0;const sl=this.prices.slice(-lb),mean=sl.reduce((a,b)=>a+b,0)/sl.length,variance=sl.reduce((a,b)=>a+Math
